replicaCount: 1

image:
  repository: docker.io/library/web-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1

service:
  type: ClusterIP
  port: 8080

resources: {}
